# Generated by Django 3.2.9 on 2021-11-29 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innovations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.ImageField(null=True, upload_to='posts'),
        ),
    ]
